# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-09-27 01:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20170511_0701'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('no', 'show')]),
        ),
    ]
