# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-10-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20180927_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatre',
            name='name',
            field=models.CharField(default='Theater Cinema', max_length=50),
        ),
    ]
